apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-ebs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: fast-ssd
  awsElasticBlockStore:
    volumeID: vol-02d0c1f843a447dc2
    fsType: ext4
