apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpadeploymentautoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  mysql
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: mysql_hpaclusterservice
  labels:
    name: mysql_hpaservice
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: mysql_hpapod
  type: ClusterIP

