apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress_deploymentautoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress_hpaclusterservice
  labels:
    name: wordpress_hpaservice
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: wordpress_hpapod
  type: ClusterIP

